# .github/workflows/verified_commits_check.yml
name: Run verified commits check

on: [push, pull_request]

jobs:
  verified_commit_check:
    name: Check for unverified commits
    runs-on: ubuntu-latest
    steps:
      - uses: nadock/verified_commits_check@v1